import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex w-full">

        <aside className="w-full max-w-[18rem] sticky  inset-0 bg-white shadow-lg border p-3  h-[calc(100vh_-_2rem)] m-[1rem] rounded-xl">
          <Sidebar />
        </aside>
        <main className="w-full my-[1rem] bg-white rounded-xl  shadow-lg border px-3" >
          {children}
        </main>
      </body>
    </html>
  );
}
